version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./config.json:/app/config.json
      - ./config.py:/app/config.py
      - ./chat_channel.py:/app/channel/chat_channel.py
